// Code generated by protoc-gen-go. DO NOT EDIT.
// source: note.proto

package note // import "github.com/taeho-io/note"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BodyType int32

const (
	BodyType_TEXT     BodyType = 0
	BodyType_HTML     BodyType = 1
	BodyType_MARKDOWN BodyType = 2
)

var BodyType_name = map[int32]string{
	0: "TEXT",
	1: "HTML",
	2: "MARKDOWN",
}
var BodyType_value = map[string]int32{
	"TEXT":     0,
	"HTML":     1,
	"MARKDOWN": 2,
}

func (x BodyType) String() string {
	return proto.EnumName(BodyType_name, int32(x))
}
func (BodyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_note_b01e1aa7ae7ebf08, []int{0}
}

type CreateRequest struct {
	CreateBy             int64    `protobuf:"varint,1,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	BodyType             BodyType `protobuf:"varint,2,opt,name=body_type,json=bodyType,proto3,enum=note.BodyType" json:"body_type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_b01e1aa7ae7ebf08, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetCreateBy() int64 {
	if m != nil {
		return m.CreateBy
	}
	return 0
}

func (m *CreateRequest) GetBodyType() BodyType {
	if m != nil {
		return m.BodyType
	}
	return BodyType_TEXT
}

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateResponse struct {
	NoteId               int64    `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_b01e1aa7ae7ebf08, []int{1}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetNoteId() int64 {
	if m != nil {
		return m.NoteId
	}
	return 0
}

type GetRequest struct {
	NoteId               int64    `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_b01e1aa7ae7ebf08, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetNoteId() int64 {
	if m != nil {
		return m.NoteId
	}
	return 0
}

type GetResponse struct {
	NoteId               int64    `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	BodyType             BodyType `protobuf:"varint,2,opt,name=body_type,json=bodyType,proto3,enum=note.BodyType" json:"body_type,omitempty"`
	CreatedBy            int64    `protobuf:"varint,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_note_b01e1aa7ae7ebf08, []int{3}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetNoteId() int64 {
	if m != nil {
		return m.NoteId
	}
	return 0
}

func (m *GetResponse) GetBodyType() BodyType {
	if m != nil {
		return m.BodyType
	}
	return BodyType_TEXT
}

func (m *GetResponse) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *GetResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "note.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "note.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "note.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "note.GetResponse")
	proto.RegisterEnum("note.BodyType", BodyType_name, BodyType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NoteClient is the client API for Note service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NoteClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type noteClient struct {
	cc *grpc.ClientConn
}

func NewNoteClient(cc *grpc.ClientConn) NoteClient {
	return &noteClient{cc}
}

func (c *noteClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/note.Note/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/note.Note/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServer is the server API for Note service.
type NoteServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterNoteServer(s *grpc.Server, srv NoteServer) {
	s.RegisterService(&_Note_serviceDesc, srv)
}

func _Note_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.Note/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Note_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/note.Note/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Note_serviceDesc = grpc.ServiceDesc{
	ServiceName: "note.Note",
	HandlerType: (*NoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Note_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Note_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "note.proto",
}

func init() { proto.RegisterFile("note.proto", fileDescriptor_note_b01e1aa7ae7ebf08) }

var fileDescriptor_note_b01e1aa7ae7ebf08 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0xdd, 0x69, 0xd2, 0x34, 0xbd, 0x6a, 0x89, 0xe3, 0x82, 0x21, 0x20, 0x84, 0xf8, 0x60, 0xd5,
	0x6d, 0x83, 0x2b, 0xe2, 0x83, 0x4f, 0x8d, 0xca, 0x2a, 0xba, 0x2b, 0x84, 0x80, 0xe2, 0x4b, 0x49,
	0x3a, 0xe3, 0x36, 0x58, 0x3b, 0xb1, 0xbd, 0x15, 0xe6, 0xd5, 0xdf, 0xf0, 0x4f, 0x7c, 0xf2, 0x3b,
	0xfc, 0x01, 0xf1, 0x2f, 0x64, 0x66, 0x12, 0x9a, 0xa8, 0xd0, 0xb7, 0x3b, 0xe7, 0xdc, 0x7b, 0x72,
	0xcf, 0xc9, 0x05, 0x58, 0x0b, 0xe4, 0xd3, 0x6a, 0x23, 0x50, 0x50, 0x5b, 0xd5, 0xc1, 0x93, 0xcb,
	0x12, 0x97, 0xbb, 0x62, 0xba, 0x10, 0x9f, 0xe2, 0x95, 0xfc, 0x80, 0xb1, 0x26, 0x17, 0x93, 0x4b,
	0xbe, 0x9e, 0x7c, 0xc9, 0x57, 0x25, 0xcb, 0x91, 0xc7, 0xff, 0x14, 0x46, 0x22, 0xfa, 0x46, 0xe0,
	0xda, 0xd3, 0x0d, 0xcf, 0x91, 0xa7, 0xfc, 0xf3, 0x8e, 0x6f, 0x91, 0xde, 0x81, 0xe1, 0x42, 0x03,
	0xf3, 0x42, 0xfa, 0x24, 0x24, 0x63, 0x2b, 0x81, 0xef, 0xbf, 0x7f, 0x58, 0xfd, 0xc8, 0x0a, 0x7f,
	0x0d, 0x52, 0xd7, 0x90, 0x89, 0xa4, 0x8f, 0x61, 0x58, 0x08, 0x26, 0xe7, 0x28, 0x2b, 0xee, 0xf7,
	0x42, 0x32, 0x1e, 0x9d, 0x8e, 0xa6, 0x7a, 0xbb, 0x44, 0x30, 0x99, 0xc9, 0x8a, 0xd7, 0x83, 0x5f,
	0x49, 0xcf, 0x23, 0xa9, 0x5b, 0xd4, 0x28, 0x3d, 0x86, 0x3e, 0x96, 0xb8, 0xe2, 0xbe, 0x15, 0x92,
	0xf1, 0x30, 0x35, 0x0f, 0x4a, 0xc1, 0x56, 0x1d, 0xbe, 0xad, 0x41, 0x5d, 0x47, 0x77, 0x61, 0xd4,
	0x2c, 0xb7, 0xad, 0xc4, 0x7a, 0xcb, 0xe9, 0x4d, 0x18, 0xa8, 0x4f, 0xcc, 0x4b, 0x66, 0x76, 0x4b,
	0x1d, 0xf5, 0x7c, 0xc9, 0xa2, 0x07, 0x00, 0x67, 0x1c, 0x1b, 0x13, 0xb7, 0xff, 0x6a, 0xeb, 0x58,
	0x68, 0x46, 0x7e, 0x12, 0xb8, 0xa2, 0x67, 0x0e, 0x68, 0xd3, 0xfb, 0x07, 0x9d, 0xb6, 0xdc, 0xdd,
	0x02, 0x30, 0x11, 0x31, 0x15, 0xa0, 0xa5, 0x85, 0xea, 0x44, 0x59, 0x22, 0xf7, 0xe6, 0xed, 0xff,
	0x99, 0xef, 0xef, 0xcd, 0xb7, 0x85, 0x72, 0xf4, 0x9d, 0x8e, 0xd0, 0x0c, 0x15, 0xbd, 0xab, 0x58,
	0x43, 0x0f, 0x0c, 0x5d, 0x23, 0x33, 0xbc, 0x77, 0x02, 0x6e, 0xb3, 0x1c, 0x75, 0xc1, 0xce, 0x9e,
	0xbf, 0xcb, 0xbc, 0x23, 0x55, 0xbd, 0xc8, 0xce, 0x5f, 0x7b, 0x84, 0x5e, 0x05, 0xf7, 0x7c, 0x96,
	0xbe, 0x7a, 0xf6, 0xe6, 0xed, 0x85, 0xd7, 0x3b, 0xfd, 0x08, 0xf6, 0x85, 0x40, 0x4e, 0x1f, 0x81,
	0x63, 0x02, 0xa7, 0x37, 0x8c, 0xc1, 0xce, 0x6d, 0x04, 0xc7, 0x5d, 0xd0, 0xe4, 0x16, 0x1d, 0xd1,
	0x13, 0xb0, 0xce, 0x38, 0x52, 0xcf, 0xd0, 0xfb, 0xff, 0x10, 0x5c, 0x6f, 0x21, 0x4d, 0x77, 0x12,
	0xbc, 0xf7, 0x5b, 0x27, 0x8b, 0x39, 0x5f, 0x8a, 0x49, 0x29, 0x62, 0xd5, 0x59, 0x38, 0xfa, 0x2c,
	0x1f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x3b, 0xe5, 0xee, 0xe7, 0x02, 0x00, 0x00,
}
