//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: note.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Note_NoteCreateCall: ClientCallUnary {}

fileprivate final class Note_NoteCreateCallBase: ClientCallUnaryBase<Note_CreateRequest, Note_CreateResponse>, Note_NoteCreateCall {
  override class var method: String { return "/note.Note/Create" }
}

internal protocol Note_NoteGetCall: ClientCallUnary {}

fileprivate final class Note_NoteGetCallBase: ClientCallUnaryBase<Note_GetRequest, Note_GetResponse>, Note_NoteGetCall {
  override class var method: String { return "/note.Note/Get" }
}

internal protocol Note_NoteListCall: ClientCallUnary {}

fileprivate final class Note_NoteListCallBase: ClientCallUnaryBase<Note_ListRequest, Note_ListResponse>, Note_NoteListCall {
  override class var method: String { return "/note.Note/List" }
}


/// Instantiate Note_NoteServiceClient, then call methods of this protocol to make API calls.
internal protocol Note_NoteService: ServiceClient {
  /// Synchronous. Unary.
  func create(_ request: Note_CreateRequest, metadata customMetadata: Metadata?) throws -> Note_CreateResponse
  /// Asynchronous. Unary.
  func create(_ request: Note_CreateRequest, metadata customMetadata: Metadata?, completion: @escaping (Note_CreateResponse?, CallResult) -> Void) throws -> Note_NoteCreateCall

  /// Synchronous. Unary.
  func get(_ request: Note_GetRequest, metadata customMetadata: Metadata?) throws -> Note_GetResponse
  /// Asynchronous. Unary.
  func get(_ request: Note_GetRequest, metadata customMetadata: Metadata?, completion: @escaping (Note_GetResponse?, CallResult) -> Void) throws -> Note_NoteGetCall

  /// Synchronous. Unary.
  func list(_ request: Note_ListRequest, metadata customMetadata: Metadata?) throws -> Note_ListResponse
  /// Asynchronous. Unary.
  func list(_ request: Note_ListRequest, metadata customMetadata: Metadata?, completion: @escaping (Note_ListResponse?, CallResult) -> Void) throws -> Note_NoteListCall

}

internal extension Note_NoteService {
  /// Synchronous. Unary.
  func create(_ request: Note_CreateRequest) throws -> Note_CreateResponse {
    return try self.create(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  func create(_ request: Note_CreateRequest, completion: @escaping (Note_CreateResponse?, CallResult) -> Void) throws -> Note_NoteCreateCall {
    return try self.create(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func get(_ request: Note_GetRequest) throws -> Note_GetResponse {
    return try self.get(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  func get(_ request: Note_GetRequest, completion: @escaping (Note_GetResponse?, CallResult) -> Void) throws -> Note_NoteGetCall {
    return try self.get(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func list(_ request: Note_ListRequest) throws -> Note_ListResponse {
    return try self.list(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  func list(_ request: Note_ListRequest, completion: @escaping (Note_ListResponse?, CallResult) -> Void) throws -> Note_NoteListCall {
    return try self.list(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Note_NoteServiceClient: ServiceClientBase, Note_NoteService {
  /// Synchronous. Unary.
  internal func create(_ request: Note_CreateRequest, metadata customMetadata: Metadata?) throws -> Note_CreateResponse {
    return try Note_NoteCreateCallBase(channel)
      .run(request: request, metadata: customMetadata ?? self.metadata)
  }
  /// Asynchronous. Unary.
  internal func create(_ request: Note_CreateRequest, metadata customMetadata: Metadata?, completion: @escaping (Note_CreateResponse?, CallResult) -> Void) throws -> Note_NoteCreateCall {
    return try Note_NoteCreateCallBase(channel)
      .start(request: request, metadata: customMetadata ?? self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func get(_ request: Note_GetRequest, metadata customMetadata: Metadata?) throws -> Note_GetResponse {
    return try Note_NoteGetCallBase(channel)
      .run(request: request, metadata: customMetadata ?? self.metadata)
  }
  /// Asynchronous. Unary.
  internal func get(_ request: Note_GetRequest, metadata customMetadata: Metadata?, completion: @escaping (Note_GetResponse?, CallResult) -> Void) throws -> Note_NoteGetCall {
    return try Note_NoteGetCallBase(channel)
      .start(request: request, metadata: customMetadata ?? self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func list(_ request: Note_ListRequest, metadata customMetadata: Metadata?) throws -> Note_ListResponse {
    return try Note_NoteListCallBase(channel)
      .run(request: request, metadata: customMetadata ?? self.metadata)
  }
  /// Asynchronous. Unary.
  internal func list(_ request: Note_ListRequest, metadata customMetadata: Metadata?, completion: @escaping (Note_ListResponse?, CallResult) -> Void) throws -> Note_NoteListCall {
    return try Note_NoteListCallBase(channel)
      .start(request: request, metadata: customMetadata ?? self.metadata, completion: completion)
  }

}

